workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - firebase_credentials
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS App (Unsigned)
        script: |
          flutter build ipa --no-codesign --verbose

      - name: Find IPA file
        script: |
          IPA_PATH=$(find build/ios/archive -name "*.ipa" | head -n 1)
          if [[ -z "$IPA_PATH" ]]; then
            echo "❌ Error: No IPA file found!"
            exit 1
          fi
          echo "✅ Found IPA file at: $IPA_PATH"
          echo "IPA_PATH=$IPA_PATH" >> $CM_ENV

      - name: Upload .ipa to Firebase App Distribution
        script: |
          if [[ -z "$IPA_PATH" ]]; then
            echo "❌ Error: IPA file not found!"
            exit 1
          fi

          curl -X POST \
            -H "Authorization: Bearer $FIREBASE_TOKEN" \
            -F "file=@$IPA_PATH" \
            -F "app_id=$FIREBASE_APP_ID" \
            -F "release_notes=New iOS build" \
            -F "testers=$FIREBASE_TESTERS" \
            https://firebaseappdistribution.googleapis.com/v1/projects/newpet-2453f/apps/$FIREBASE_APP_ID/releases

artifacts:
  - build/ios/archive/*.ipa
