workflows:
  ios:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean the build
        script: |
          flutter clean
          cd ios
          pod install
          cd ..
      - name: Build iOS IPA file without code signing
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
