workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Install Dependencies
        script: |
          flutter clean
          cd ios
          pod install --verbose --repo-update
          cd ..
      - name: Build iOS Without Code Signing
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
