workflows:
  ios-build:
    name: iOS Build (Without Code Signing)
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: 15.0
      cocoapods: default
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Clean iOS dependencies
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod deintegrate
          pod install --repo-update
          cd ..

      - name: Ensure iOS Deployment Target is 12.0
        script: |
          sed -i '' 's/platform :ios, .*/platform :ios, "12.0"/' ios/Podfile

      - name: Clean and Build iOS app (Without Code Signing)
        script: |
          flutter clean
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/*.app
      - build/ios/archive/*.xcarchive
