workflows:
  ios:
    name: Build iOS App
    environment:
      flutter: stable
    scripts:
      - name: Clean and Install Dependencies
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install
          cd ..

      # Step 2: Build the iOS app and generate .ipa
      - name: Build the iOS app and generate .ipa
        script: |
          flutter build ios --release --no-codesign
          cd ios
          # Archive the app
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -sdk iphoneos -archivePath build/ios/archive/Runner.xcarchive archive
          # Export the .ipa file
          xcodebuild -exportArchive -archivePath build/ios/archive/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/ios/ipa
          cd ..
