workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - firebase_credentials
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Clean CocoaPods Cache
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod deintegrate
          pod install --repo-update
          cd ..

      - name: Build iOS IPA (Unsigned)
        script: |
          flutter build ios --no-codesign --verbose
          mkdir -p build/ios/ipa
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ios/archive/Runner.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO DEVELOPMENT_TEAM=""

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/exportOptions.plist

      - name: Find IPA file
        script: |
          IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -n 1)
          if [[ -z "$IPA_PATH" ]]; then
            echo "❌ No IPA file found!"
            exit 1
          fi
          echo "✅ IPA found at: $IPA_PATH"
          echo "IPA_PATH=$IPA_PATH" >> $CM_ENV

      - name: Upload IPA to Firebase App Distribution
        script: |
          if [[ -z "$IPA_PATH" ]]; then
            echo "❌ IPA file not found!"
            exit 1 
          fi

          curl -X POST \
            -H "Authorization: Bearer $FIREBASE_TOKEN" \
            -F "file=@$IPA_PATH" \
            -F "app_id=$FIREBASE_APP_ID" \
            -F "release_notes=New iOS build for testing" \
            -F "testers=$FIREBASE_TESTERS" \
            https://firebaseappdistribution.googleapis.com/v1/projects/YOUR_PROJECT_ID/apps/$FIREBASE_APP_ID/releases

artifacts:
  - build/ios/ipa/*.ipa
