workflows:
  ios_release:
    name: iOS Release
    instance_type: macos
    environment:
      flutter: stable
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.ipa
    publish:
      firebase:
        token: $FIREBASE_TOKEN
        groups: testers
        file: build/ios/iphoneos/Runner.ipa
