workflows:
  ios_build:
    name: Build and Distribute iOS App
    instance_type: mac_mini_m1  # Ensure your billing plan supports this instance

    environment:
      vars:
        FIREBASE_APP_ID: "1:430197957945:ios:7027d28210ae90c8a8b4e8"
        TESTER_GROUPS: "yasmen"
      flutter: stable  # Ensures you’re using the latest Flutter stable release

    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --release --no-codesign  # Builds iOS release version without signing
      - xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner archive -archivePath $PWD/build/ios/archive/Runner.xcarchive -configuration Release -sdk iphoneos
      - xcodebuild -exportArchive -archivePath $PWD/build/ios/archive/Runner.xcarchive -exportPath $PWD/build/ios/ipa -exportOptionsPlist ios/ExportOptions.plist
      - curl -sL https://firebase.tools | bash
      - firebase appdistribution:distribute build/ios/ipa/Runner.ipa --app $FIREBASE_APP_ID --groups "$TESTER_GROUPS"
