workflows:
  ios:
    name: iOS Development Workflow
    max_build_duration: 120
    build:
      ios:
        scheme: "ios-development"
        release: false

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      # Android build section
      - name: Build Android app
        script: |
          flutter build apk --release

      # iOS build section
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign

      # iOS distribution (optional step, if you want to distribute the app)
      - name: Distribute iOS app
        script: |
          flutter build ios --release --export-method ad-hoc
