name: youssef
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.10
  provider: ^6.1.2
  workmanager: ^0.5.2
  firebase_cloud_firestore: ^5.4.4
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  firebase_auth: ^5.4.0
  google_api_availability: ^5.0.0
  printing: ^5.11.0
  pdf: ^3.10.4
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  flutter_local_notifications: ^18.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pet.gif
    - assets/one.png
    - assets/two.png
    - assets/three.png
    - assets/four.png
    - assets/five.png
    - assets/six.png
    - assets/pet.png
    - assets/alarm.png
    - assets/pen.gif
    - assets/cavnva.png
    - assets/edit.png
    - assets/ostor.png
    - assets/doc.png
