platform :ios, '12.0'

target 'Runner' do


  pod 'Firebase/Core', '~> 10.0.0'  
  pod 'Firebase/Firestore', '~> 10.0.0'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end