# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# Uncomment the next line if you don't want to use dynamic frameworks
# use_frameworks!

target 'Runner' do
  # Uncomment the next line if you want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  # Add any other Firebase pods you might be using, like:
  # pod 'Firebase/Auth'
  # pod 'Firebase/Messaging'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# Post-install hook to modify build settings
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # Handling BoringSSL-GRPC issue with flags
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end
end
